#! /usr/bin/env python3

'''
This node is used to collect data from the Turtlebot3LIDAR and save it into a csv file
'''

import rospy
from sensor_msgs.msg import LaserScan
from matplotlib import pyplot as plt
import numpy as np

fig, ax = plt.subplots(1, 1, figsize=(4, 4), tight_layout=True)

# BEGIN MEASUREMENT 
def scan_callback(msg):

    strRange = [str(x) for x in msg.ranges]
    rangeStr = ",".join(strRange) + "\n"
    file1 = open("/home/chen2156/laserData/src/laser_values/src/laserDataCaputer.txt","a")
    file1.write(rangeStr)
    file1.close()
#END MEASUREMENT  

rospy.init_node('range_ahead')
scan_sub = rospy.Subscriber('scan', LaserScan, scan_callback)
rospy.spin()
